# Generated by Django 2.0 on 2018-03-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.IntegerField(choices=[(1, '待支付'), (2, '已取消'), (3, '待接单'), (4, '待发货'), (5, '已发货'), (6, '已完成'), (7, '已确认收货'), (8, '申请延期'), (9, '确认延期'), (10, '退款'), (11, '退货'), (12, '作废')], default=1, help_text='订单状态', verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderlogistics',
            name='order',
            field=models.CharField(help_text='订单号', max_length=17, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orderoperationrecord',
            name='status',
            field=models.IntegerField(choices=[(1, '提交订单'), (2, '支付订单'), (3, '取消订单'), (4, '待接单'), (5, '接单'), (6, '发货'), (7, '无货'), (8, '确认延期')], default=1, help_text='订单状态', verbose_name='订单状态'),
        ),
    ]
