# Generated by Django 2.0 on 2018-03-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180302_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlogistics',
            old_name='order',
            new_name='order_sn',
        ),
    ]
