# Generated by Django 2.0 on 2018-03-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180302_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_sn', models.IntegerField(help_text='发票编号', verbose_name='发票编号')),
                ('order_sn', models.CharField(help_text='订单号', max_length=17, verbose_name='订单号')),
                ('images', models.URLField(help_text='发票照片', verbose_name='发票照片')),
                ('remarks', models.TextField(default='', help_text='备注', verbose_name='备注')),
            ],
            options={
                'verbose_name': '开票记录',
                'verbose_name_plural': '开票记录',
            },
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': '发票抬头', 'verbose_name_plural': '发票抬头'},
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='delivery_time',
            field=models.DateTimeField(blank=True, help_text='发货时间', null=True, verbose_name='发货时间'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='due_desc',
            field=models.TextField(blank=True, help_text='延期说明', null=True, verbose_name='延期说明'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='due_time',
            field=models.DateField(blank=True, help_text='到期时间', null=True, verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='max_delivery_time',
            field=models.IntegerField(blank=True, help_text='最大发货日期', null=True, verbose_name='最大发货日期'),
        ),
        migrations.AlterField(
            model_name='orderoperationrecord',
            name='status',
            field=models.IntegerField(choices=[(1, '提交订单'), (2, '支付订单'), (3, '取消订单'), (4, '待接单'), (5, '接单'), (6, '发货'), (7, '确认收货'), (8, '无货'), (9, '确认延期')], default=1, help_text='订单状态', verbose_name='订单状态'),
        ),
    ]
