# Generated by Django 2.0 on 2018-03-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180303_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openreceipt',
            old_name='images_url',
            new_name='images',
        ),
    ]
