# Generated by Django 2.0 on 2018-03-03 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180303_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='openreceipt',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='openreceipt',
            name='remarks',
            field=models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.IntegerField(choices=[(1, '待支付'), (2, '已取消'), (3, '待接单'), (4, '待发货'), (5, '已发货'), (6, '已确认收货'), (7, '已完成'), (8, '申请延期'), (9, '确认延期'), (10, '退款'), (11, '退货'), (12, '作废')], default=1, help_text='订单状态', verbose_name='订单状态'),
        ),
    ]
