# Generated by Django 2.0 on 2018-03-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180303_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openreceipt',
            name='receipt_sn',
            field=models.CharField(help_text='发票编号', max_length=30, verbose_name='发票编号'),
        ),
    ]
