# Generated by Django 2.0 on 2018-03-05 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180303_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(help_text='订单号', max_length=17, verbose_name='订单号')),
                ('abnormal_type', models.IntegerField(choices=[(1, '无货'), (2, '延期')], default=1, help_text='异常类型', verbose_name='异常类型')),
                ('remarks', models.TextField(default='', help_text='客户备注', verbose_name='客户备注')),
                ('original_delivery_time', models.DateField(blank=True, help_text='原发货日', null=True, verbose_name='原发货日')),
                ('expect_date_of_delivery', models.DateField(blank=True, help_text='预计发货日', null=True, verbose_name='预计发货日')),
                ('is_deal', models.IntegerField(choices=[(1, '未处理'), (2, '已处理')], default=1, help_text='是否处理', verbose_name='是否处理')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '异常订单',
                'verbose_name_plural': '异常订单',
            },
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.IntegerField(choices=[(1, '待支付'), (2, '已取消'), (3, '待接单'), (4, '待发货'), (5, '已发货'), (6, '已完成'), (8, '申请延期'), (10, '退款'), (11, '退货'), (12, '作废'), (13, '无货')], default=1, help_text='订单状态', verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderoperationrecord',
            name='status',
            field=models.IntegerField(choices=[(1, '提交订单'), (2, '支付订单'), (3, '取消订单'), (4, '待接单'), (5, '接单'), (6, '发货'), (7, '确认收货'), (8, '无货'), (9, '确认延期'), (10, '申请延期')], default=1, help_text='订单状态', verbose_name='订单状态'),
        ),
    ]
