# Generated by Django 2.0 on 2018-03-05 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180305_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUserOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(help_text='订单号', max_length=17, verbose_name='订单号')),
                ('operator', models.IntegerField(help_text='操作人', verbose_name='操作人')),
                ('original_status', models.IntegerField(help_text='原状态', verbose_name='原状态')),
                ('changed_status', models.IntegerField(help_text='改变后状态', verbose_name='改变后状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '超级管理员操作',
                'verbose_name_plural': '超级管理员操作',
            },
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.IntegerField(choices=[(1, '待支付'), (2, '已取消'), (3, '待接单'), (4, '待发货'), (5, '已发货,配送中'), (6, '已完成'), (8, '申请延期中'), (10, '退款'), (11, '退货'), (12, '作废'), (13, '无货')], default=1, help_text='订单状态', verbose_name='订单状态'),
        ),
    ]
