# Generated by Django 2.0 on 2018-03-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180309_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnsdeal',
            name='return_type',
            field=models.IntegerField(choices=[(1, '退货'), (2, '退款')], default=1, help_text='退货类型', verbose_name='退货类型'),
        ),
        migrations.AlterField(
            model_name='orderreturns',
            name='returns_type',
            field=models.IntegerField(choices=[(1, '退货'), (2, '退款')], default=1, help_text='退货类型', verbose_name='退货类型'),
        ),
    ]
