# Generated by Django 2.0 on 2018-03-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20180309_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreturns',
            name='handling_time',
        ),
        migrations.RemoveField(
            model_name='orderreturns',
            name='logistics_type',
        ),
        migrations.RemoveField(
            model_name='orderreturns',
            name='returns_handling_way',
        ),
        migrations.RemoveField(
            model_name='orderreturns',
            name='returns_money',
        ),
        migrations.RemoveField(
            model_name='orderreturns',
            name='returns_reason',
        ),
        migrations.RemoveField(
            model_name='orderreturns',
            name='returns_submit_time',
        ),
        migrations.RemoveField(
            model_name='orderreturns',
            name='returns_type',
        ),
    ]
