# Generated by Django 2.0 on 2018-03-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20180309_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreturns',
            name='date_of_delivery',
        ),
        migrations.AddField(
            model_name='orderreturns',
            name='status',
            field=models.IntegerField(choices=[(1, '待收货'), (2, '确认收货')], default=1, help_text='状态', verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='company_name',
            field=models.CharField(default='', help_text='公司名称', max_length=200, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='orderoperationrecord',
            name='status',
            field=models.IntegerField(choices=[(1, '提交订单'), (2, '支付订单'), (3, '取消订单'), (4, '待接单'), (5, '接单'), (6, '发货'), (7, '客户确认收货'), (8, '申请无货'), (9, '确认延期'), (10, '申请延期'), (11, '申请退款'), (12, '申请退货'), (13, '同意退货'), (14, '供应商确认收货'), (15, '确认退款'), (16, '确认无货'), (17, '填写退货物流')], default=1, help_text='订单状态', verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderreturns',
            name='returns_sn',
            field=models.CharField(help_text='退货单号', max_length=20, verbose_name='退货单号'),
        ),
    ]
