# Generated by Django 2.0 on 2018-03-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20180310_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='company_name',
        ),
    ]
