# Generated by Django 2.0 on 2018-03-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_receipt_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderoperationrecord',
            name='is_abnormal',
            field=models.BooleanField(default=False, help_text='是否异常', verbose_name='是否异常'),
        ),
    ]
