# Generated by Django 2.0 on 2018-03-12 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderoperationrecord_is_abnormal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(default='', help_text='订单号', max_length=17, verbose_name='订单号')),
                ('refund_sn', models.CharField(help_text='退款单号', max_length=20, verbose_name='退款单号')),
                ('amount', models.FloatField(default=0.0, help_text='退款金额', verbose_name='退款金额')),
                ('status', models.IntegerField(choices=[(1, '等待退款'), (2, '退款完成')], default=1, help_text='状态', verbose_name='状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '订单退款',
                'verbose_name_plural': '订单退款',
            },
        ),
        migrations.AddField(
            model_name='abnormalorder',
            name='responsible_party',
            field=models.IntegerField(choices=[(1, '客户'), (2, '供应商'), (3, '平台')], default=1, help_text='责任方', verbose_name='责任方'),
        ),
        migrations.AlterField(
            model_name='orderoperationrecord',
            name='status',
            field=models.IntegerField(choices=[(1, '提交订单'), (2, '支付订单'), (3, '取消订单'), (4, '待接单'), (5, '接单'), (6, '发货'), (7, '客户确认收货'), (8, '申请无货'), (9, '确认延期'), (10, '申请延期'), (11, '系统生成退款单'), (12, '申请退货'), (13, '同意退货'), (14, '供应商确认收货'), (15, '确认退款'), (16, '确认无货'), (17, '填写退货物流')], default=1, help_text='订单状态', verbose_name='订单状态'),
        ),
    ]
