# Generated by Django 2.0 on 2018-03-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20180312_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_company_name',
            field=models.CharField(default='', help_text='客户公司名', max_length=100, verbose_name='客户公司名'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='goods_name',
            field=models.CharField(default='', help_text='商品名', max_length=100, verbose_name='商品名'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='supplier_name',
            field=models.CharField(default='', help_text='供应商名', max_length=100, verbose_name='供应商名'),
        ),
    ]
