# Generated by Django 2.0 on 2018-03-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20180312_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='guest_company_name',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='guest_company_name',
            field=models.CharField(default='', help_text='客户公司名', max_length=100, verbose_name='客户公司名'),
        ),
    ]
