# Generated by Django 2.0 on 2018-03-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_orderdetail_goods_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='', help_text='市', max_length=50, verbose_name='市'),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, default='', help_text='区', max_length=50, verbose_name='区'),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, default='', help_text='省', max_length=50, verbose_name='省'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='goods_sn',
            field=models.CharField(default='', help_text='商品号', max_length=17, verbose_name='商品号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(help_text='详细地址', max_length=200, verbose_name='详细地址'),
        ),
    ]
