# Generated by Django 2.0 on 2018-03-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20180315_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='min_buy',
        ),
    ]
