# Generated by Django 2.0 on 2018-03-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_orderdetail_min_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlogistics',
            name='sender',
            field=models.CharField(default='', help_text='送货人', max_length=30, verbose_name='送货人'),
        ),
    ]
