# Generated by Django 2.0 on 2018-03-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_orderlogistics_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturns',
            name='sender',
            field=models.CharField(default='', help_text='送货人', max_length=30, verbose_name='送货人'),
        ),
        migrations.AlterField(
            model_name='orderlogistics',
            name='date_of_delivery',
            field=models.DateField(blank=True, help_text='最大发货日', null=True, verbose_name='最大发货日'),
        ),
    ]
