# Generated by Django 2.0 on 2018-03-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20180316_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderoperationrecord',
            name='remarks',
            field=models.TextField(default='', help_text='客户备注', verbose_name='客户备注'),
        ),
    ]
