# Generated by Django 2.0 on 2018-03-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_orderrefund_return_sn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrefund',
            old_name='return_sn',
            new_name='returns_sn',
        ),
    ]
