# Generated by Django 2.0 on 2018-03-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20180316_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnsdeal',
            name='return_sn',
            field=models.CharField(default='', help_text='退货退款单号', max_length=20, verbose_name='退货退款单号'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.IntegerField(choices=[(1, '待支付'), (2, '已取消'), (3, '待接单'), (4, '待发货'), (5, '已发货,配送中'), (6, '已完成'), (8, '申请延期中'), (10, '退款中'), (11, '退货中'), (12, '作废'), (13, '无货'), (14, '退款完成'), (15, '退货完成'), (16, '订单流转结束')], default=1, help_text='订单状态', verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderreturns',
            name='status',
            field=models.IntegerField(choices=[(1, '待收货'), (2, '确认收货'), (3, '待审核'), (4, '审核未通过')], default=3, help_text='状态', verbose_name='状态'),
        ),
    ]
