# Generated by Django 2.0 on 2018-03-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20180319_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormalorder',
            name='is_pass',
            field=models.BooleanField(default=False, help_text='是否通过审核', verbose_name='是否通过审核'),
        ),
        migrations.AlterField(
            model_name='orderreturns',
            name='status',
            field=models.IntegerField(choices=[(1, '待收货'), (2, '确认收货'), (3, '待审核'), (4, '审核未通过'), (5, '待上传物流信息')], default=3, help_text='状态', verbose_name='状态'),
        ),
    ]
